name = "isghost"
main = "src/index.js"
compatibility_date = "2024-11-01"

[[d1_databases]]
binding = "DB"
database_name = "acs-notify"
database_id = "ec88a757-c97c-45f5-88f8-fe0801aa2055"

[vars]
OWNER_IDS = "7654150612"
PANEL_URL = "https://interlink-panel.hamid-ab-dev.workers.dev"
INTERLINK_API_BASE = "https://prod.interlinklabs.ai/api/v1"
BOT_USERNAME = "ambassadorITLbot"
BOT_APP_SHORT_NAME = "rank"
